databases:
  - name: shop
    databaseName: postgres_sql
    user: postgres_sql_user

services:
  - type: web
    name: shop
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn shop.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shop
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
